volumes:
  telegram_content_scrapper_local_postgres_data: {}
  telegram_content_scrapper_local_postgres_data_backups: {}
  telegram_content_scrapper_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: telegram_content_scrapper_local_django
    container_name: telegram_content_scrapper_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8080:8000'
    command: /start
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: telegram_content_scrapper_production_postgres
    container_name: telegram_content_scrapper_local_postgres
    volumes:
      - telegram_content_scrapper_local_postgres_data:/var/lib/postgresql/data
      - telegram_content_scrapper_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    restart: unless-stopped

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: telegram_content_scrapper_local_mailpit
    ports:
      - "8085:8025"
    restart: unless-stopped

  redis:
    image: docker.io/redis:6
    container_name: telegram_content_scrapper_local_redis
    
    volumes:
      - telegram_content_scrapper_local_redis_data:/data
    restart: unless-stopped
    

  celeryworker:
    <<: *django
    image: telegram_content_scrapper_local_celeryworker
    container_name: telegram_content_scrapper_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker
    restart: unless-stopped

  celerybeat:
    <<: *django
    image: telegram_content_scrapper_local_celerybeat
    container_name: telegram_content_scrapper_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat
    restart: unless-stopped

  flower:
    <<: *django
    image: telegram_content_scrapper_local_flower
    container_name: telegram_content_scrapper_local_flower
    ports:
      - '8555:5555'
    command: /start-flower
    restart: unless-stopped
