services:
  docs:
    image: telegram_content_scrapper_local_docs
    container_name: telegram_content_scrapper_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./telegram_content_scrapper:/app/telegram_content_scrapper:z
    ports:
      - '9000:9000'
    command: /start-docs
