# Generated by Django 5.0.12 on 2025-02-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
