# Generated by Django 5.0.12 on 2025-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_phone_number',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
