# Generated by Django 5.0.12 on 2025-02-28 04:58

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_telegram_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
