# Generated by Django 5.0.12 on 2025-02-28 08:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0002_telethonsession_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='telethonsession',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
