# Generated by Django 5.0.12 on 2025-02-28 08:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0003_telethonsession_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telethonsession',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
