# Generated by Django 5.0.12 on 2025-03-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0004_alter_telethonsession_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramEntityInfo',
        ),
    ]
