# Generated by Django 5.0.12 on 2025-03-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0005_delete_telegramentityinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
