# Generated by Django 5.0.12 on 2025-03-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0006_testdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDb',
        ),
    ]
