# Generated by Django 5.0.12 on 2025-03-07 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0007_delete_testdb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.BigIntegerField(db_index=True)),
                ('entity_type', models.CharField(max_length=16)),
                ('entity_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramEntityContentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.BigIntegerField(db_index=True)),
                ('entity_text_content', models.TextField(blank=True)),
                ('entity_content_url', models.TextField(blank=True)),
                ('entity_post_timestamp', models.DateTimeField()),
                ('processed_text_content', models.TextField(blank=True)),
                ('date_in_text_content', models.CharField(blank=True, max_length=16)),
                ('time_in_text_content', models.CharField(blank=True, max_length=16)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_scrapper.telegramentity')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_still_linked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_scrapper.telegramentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
