# Generated by Django 5.0.12 on 2025-03-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0008_telegramentity_telegramentitycontentdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramentitycontentdata',
            name='is_downloaded',
        ),
        migrations.AddField(
            model_name='telegramuserentity',
            name='latest_downloaded_msg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_scrapper.telegramentitycontentdata'),
        ),
    ]
