# Generated by Django 5.0.12 on 2025-03-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0010_telegramentitycontentdata_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramentitycontentdata',
            old_name='msg_id',
            new_name='content_id',
        ),
    ]
