# Generated by Django 5.0.12 on 2025-03-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0011_rename_msg_id_telegramentitycontentdata_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramentitycontentdata',
            name='entity_media_data_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramentitycontentdata',
            name='entity_media_data_type',
            field=models.CharField(blank=True),
        ),
    ]
