# Generated by Django 5.0.12 on 2025-03-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0012_telegramentitycontentdata_entity_media_data_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuserentity',
            old_name='latest_downloaded_msg',
            new_name='latest_downloaded_content',
        ),
        migrations.AddField(
            model_name='telegramentitycontentdata',
            name='text_content_hashtags',
            field=models.TextField(blank=True),
        ),
    ]
