# Generated by Django 5.0.12 on 2025-03-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0013_rename_latest_downloaded_msg_telegramuserentity_latest_downloaded_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramentitycontentdata',
            name='date_in_text_content',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='telegramentitycontentdata',
            name='time_in_text_content',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
