# Generated by Django 5.0.12 on 2025-03-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_scrapper', '0014_alter_telegramentitycontentdata_date_in_text_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuserentity',
            name='latest_downloaded_content',
        ),
        migrations.RemoveField(
            model_name='telegramuserentity',
            name='telegram_entity',
        ),
        migrations.RemoveField(
            model_name='telegramuserentity',
            name='user',
        ),
        migrations.DeleteModel(
            name='TelegramEntityContentData',
        ),
        migrations.DeleteModel(
            name='TelegramUserEntity',
        ),
    ]
